image: git.panter.ch:5001/open-source/aoz-003/gitlab_ci:2.6.6

stages:
  - test

services:
  - postgres:9.6

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB'
  POSTGRES_HOST_AUTH_METHOD: trust

.pull-push-cash:
  cache:
    key: aoz-003-ruby-2-6-6
    paths:
      - tmp/cache/ruby
      - tmp/cache/yarn
      - tmp/cache/webdrivers
    policy: pull-push

.pull-cache:
  cache:
    key: aoz-003-ruby-2-6-6
    paths:
      - tmp/cache/ruby
      - tmp/cache/yarn
      - tmp/cache/webdrivers
    policy: pull

.test-extend:
  stage: test
  before_script:
    - yarn install --cache-folder tmp/cache/yarn
    - bundle config set path 'tmp/cache'
    - bundle install
    - bundle exec rails db:schema:load

.update_webdrivers: &update_webdrivers |
  function update_webdrivers_task() {
    if ! [ -f "tmp/cache/webdrivers/chromedriver" ]; then
      echo "webdrivers are not cached and thus need to be updated/fetched"
      bundle exec rake webdrivers:chromedriver:update
    fi
  }

.retry-dropped-runners:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - job_execution_timeout
      - scheduler_failure
      - stale_schedule

lint:
  extends:
    - .pull-push-cash
    - .test-extend
  script:
    # only for having crhomedriver in the cache (this job is the only one pushing the cache)
    - *update_webdrivers
    - update_webdrivers_task
    - yarn lint:js
    - bundle exec rubocop
    - yarn lint:css

test:
  extends:
    - .pull-cache
    - .test-extend
    - .retry-dropped-runners
  script:
    - bundle exec rails test

system:
  extends:
    - .pull-cache
    - .test-extend
    - .retry-dropped-runners
  script:
    - *update_webdrivers
    - update_webdrivers_task
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
