include:
  - project: gitlab-ci/rails-testing
    ref: v1
    file: rails-testing.yml

image: git.panter.ch:5001/open-source/aoz-003/gitlab_ci:2.6.6

stages:
  - test

services:
  - postgres:9.6

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB'
  POSTGRES_HOST_AUTH_METHOD: trust

lint:
  stage: test
  retry: 0
  extends:
    - .cache-pull-push
    - .retry-dropped-runners
    - .bundle-yarn-install-webdrivers-chrome
  script:
    - bundle exec rails db:schema:load # some RuboCop cops require it
    - yarn lint:js
    - yarn lint:css
    - bundle exec rubocop

test:
  stage: test
  retry: 0
  extends:
    - .cache-pull
    - .retry-dropped-runners
    - .bundle-yarn-install
  script:
    - bundle exec rails db:schema:load
    - bundle exec rails test
  artifacts:
    reports:
      cobertura: coverage/coverage.xml

system:
  stage: test
  retry: 1
  variables:
    TEST_TYPE: ':system'
  extends:
    - .cache-pull
    - .retry-dropped-runners
    - .bundle-yarn-install-webdrivers-chrome
    - .capybara-screenshot-artifacts
  script:
    - bundle exec rails db:schema:load
    - bundle exec rails test:system
  artifacts:
    reports:
      cobertura: coverage/coverage.xml
