image: nbulai/ruby-chromedriver:2.35

stages:
  - test

services:
  - postgres:9.6

cache:
  paths:
    - vendor/ruby

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"

before_script:
  - gem update --system
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec chromedriver-update 2.36
  - ruby --version
  - google-chrome --version
  - bundle exec chromedriver --version
  - bundle exec rails db:schema:load

test:
  stage: test
  script:
    - bundle exec rails test
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
