image: git.panter.ch:5001/open-source/aoz-003/gitlab_ci:2.6.6

stages:
  - test

services:
  - postgres:9.6

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB'
  POSTGRES_HOST_AUTH_METHOD: trust

.push-pull-cache:
  cache:
    key: aoz-003-ruby-2-6-6
    paths:
      - tmp/cache/ruby
      - tmp/cache/yarn
    policy: pull-push

.pull-cache:
  cache:
    key: aoz-003-ruby-2-6-6
    paths:
      - tmp/cache/ruby
      - tmp/cache/yarn
    policy: pull

.test-extend:
  stage: test
  before_script:
    - bundle install --without development --path tmp/cache
    - yarn install --cache-folder tmp/cache/yarn
    - bundle exec rails db:schema:load

.retry-dropped-runners:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - job_execution_timeout
      - scheduler_failure
      - stale_schedule

test:
  extends:
    - .push-pull-cache
    - .test-extend
    - .retry-dropped-runners
  script:
    - bundle exec rails test

system:
  extends:
    - .pull-cache
    - .test-extend
    - .retry-dropped-runners
  script:
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
