image: git.panter.ch:5001/panter/gitlab-ci-docker-images/ruby-and-rails:ruby-2.4.4-imagemagick-node-8-chrome

stages:
  - test

services:
  - postgres:9.6

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - tmp/cache/ruby
    - tmp/cache/yarn

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"

before_script:
  - node --version
  - ruby --version
  - yarn --version
  - bundle install --without development --path tmp/cache
  - yarn install --cache-folder tmp/cache/yarn
  - bundle exec rails db:schema:load

test:
  stage: test
  script:
    - bundle exec rails test

system:
  stage: test
  script:
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
  cache:
    policy: pull
