image: git.panter.ch:5001/panter/gitlab-ci-docker-images/ruby-and-rails:ruby-2.4.5-node8-chrome-imagemagick-chromedriver

stages:
  - test

services:
  - postgres:9.6

cache:
  key: "$CI_PROJECT_ID"
  paths:
    - tmp/cache/ruby
    - tmp/cache/yarn

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - google-chrome --version
  - node --version
  - ruby --version
  - yarn --version
  - gem install bundler
  - bundle install --without development --path tmp/cache
  - yarn install --cache-folder tmp/cache/yarn
  - bundle exec rails db:schema:load

test:
  stage: test
  script:
    - bundle exec rails test

system:
  stage: test
  script:
    - CHROME_VERSION=$(google-chrome --version | sed -r 's/[^0-9]+([0-9]+\.[0-9]+\.[0-9]+).*/\1/g')
    - CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
    - bundle exec chromedriver-update $CHROMEDRIVER_VERSION
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
  cache:
    policy: pull
