stages:
  - test

services:
  - postgres:9.6

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"

before_script:
  - bundle install --path vendor
  - bundle exec rails db:schema:load

test:
  image: git.panter.ch:5001/open-source/aoz-003/unit:2.4.4
  stage: test
  script:
    - bundle exec rails test
  cache:
    paths:
      - vendor

system:
  image: git.panter.ch:5001/open-source/aoz-003/system:2.36
  stage: test
  script:
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
  cache:
    policy: pull
    paths:
      - vendor
