image: git.panter.ch:5001/open-source/aoz-003

stages:
  - test

services:
  - postgres:9.6

cache:
  paths:
    - vendor

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"

before_script:
  - bundle install -j $(nproc) --path vendor
  - bundle exec rails db:schema:load

test:
  stage: test
  script:
    - bundle exec rails test

system_test:
  stage: test
  script:
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
