image: git.panter.ch:5001/panter/gitlab-ci-docker-images/ruby-and-rails:ruby-2.4.5-node8-chrome-imagemagick-chromedriver

stages:
  - test

services:
  - postgres:9.6

variables:
  RAILS_ENV: test
  POSTGRES_DB: aoz_test
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/$POSTGRES_DB"
  POSTGRES_HOST_AUTH_METHOD: trust

.push-pull-cache:
  cache:
    paths:
      - tmp/cache/ruby
      - tmp/cache/yarn
    policy: pull-push


.pull-cache:
  cache:
    paths:
      - tmp/cache/ruby
      - tmp/cache/yarn
    policy: pull


.test-extend:
  stage: test
  before_script:
    - gem install bundler --version 2.0.2
    - bundle install --without development --path tmp/cache
    - yarn install --cache-folder tmp/cache/yarn
    - bundle exec rails db:schema:load

test:
  extends:
    - .push-pull-cache
    - .test-extend
  script:
    - bundle exec rails test

system:
  extends:
    - .pull-cache
    - .test-extend
  script:
    - CHROME_VERSION=$(google-chrome --version | sed -r 's/[^0-9]+([0-9]+\.[0-9]+\.[0-9]+).*/\1/g')
    - CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
    - bundle exec chromedriver-update $CHROMEDRIVER_VERSION
    - bundle exec rails test:system
  artifacts:
    paths:
      - tmp/screenshots
    when: on_failure
    expire_in: 1 week
