AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'tmp/**/*'
    - vendor/**/*
    - Rakefile
    - config/boot.rb
  DisplayCopNames: true

Rails:
  Enabled: true

Style/Alias:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FormatString:
  EnforcedStyle: percent
Style/AsciiComments:
  Enabled: false
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/seeds.rb'
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
    - 'db/seeds.rb'

Metrics/AbcSize:
  Max: 19
  Exclude:
    - 'test/**/*'
    - 'db/seeds.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/system/*'
    - 'db/seeds.rb'
    - 'config/routes.rb'

Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/WordArray:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
