inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'tmp/**/*'
    - vendor/**/*
    - Rakefile
    - config/boot.rb
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.6

Rails:
  Enabled: true
Rails/FilePath:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/RefuteMethods:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - test/**/*
    - db/seeds.rb
  Max: 25
Metrics/ClassLength:
  Exclude:
    - test/**/*
  Max: 150
Metrics/MethodLength:
  Exclude:
    - test/**/*
    - db/seeds.rb
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'test/system/*'
    - 'db/seeds.rb'
    - 'config/routes.rb'
  ExcludedMethods:
    - included # for concerns
    - draw # for routes
    - define # for FactoryBot
    - factory

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_inspect
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_first_parameter
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_first_argument
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: false
  # The IgnoredPatterns option is a list of !ruby/regexp and/or string
  # elements. Strings will be converted to Regexp objects. A line that matches
  # any regular expression listed in this option will be ignored by LineLength.
  IgnoredPatterns: []

Style/Alias:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  MinBodyLength: 5
Style/IfUnlessModifier:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
  EnforcedStyle: slashes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  Enabled: false
Style/HashTransformValues:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
