language: ruby

cache:
  bundler: true
  directories:
    - vendor
    - .rvm

services: postgresql

addons:
  chrome: stable
  postgresql: "9.4"

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3

script:
  - bundle exec rails test
  - bundle exec rails test:system
