language: ruby

cache: bundler

services: postgresql

before_script:
  - bundle exec rails db:drop
  - bundle exec rails db:create
  - bundle exec rails db:schema:load

script:
  - bundle exec rails test
  - bundle exec rails test:system
