language: ruby

cache:
  bundler: true
  directories:
    - .phantomjs
    - .rvm

services: postgresql

addons:
  postgresql: "9.4"

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load

script:
  - bundle exec rails test
  - bundle exec rails test:system
