language: ruby

rvm:
  - 2.4.1

env:
  - RAILS_ENV=test

cache:
  - bundler


services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database aoz-github_test;' -U postgres

script:
  - bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
  - bundle exec rails test
