language: ruby

rvm:
  - 2.4.1

cache:
  - bundler

env:
  - DB=postgres

services:
  - postgresql

before_script:
  - sh -c "psql -c 'DROP DATABASE IF EXISTS aoz-github_test;' -U postgres"
  - sh -c "psql -c 'DROP DATABASE IF EXISTS aoz-github_test_tmp;' -U postgres"
  - sh -c "psql -c 'CREATE DATABASE aoz-github_test;' -U postgres"
  - sh -c "psql -c 'CREATE DATABASE aoz-github_test_tmp;' -U postgres"

script:
  - bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rails test
