language: ruby

rvm:
  - 2.4.1

cache:
  - bundler

env: LC_ALL="en_US.UTF-8"

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - rm /var/run/postgresql/.s.PGSQL.*
  - service postgresql restart
  - psql -c 'create database aoz-github_test;' -U postgres

script:
  - bundle exec rails db:setup
  - bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rails test
