language: ruby

rvm:
  - 2.4.1

cache:
  - bundler

env:
  - DB=postgres

services:
  - postgresql

addons:
  - postgresql: "9.6"

before_install:
  - service postgresql stop
  - service postgresql start

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS aoz-github_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS aoz-github_test_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE aoz-github_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE aoz-github_test_tmp;' -U postgres; fi"

script:
  - bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rails test
