language: ruby

cache:
  bundler: true
  directories:
    - .phantomjs

services: postgresql

addons:
  postgresql: "9.4"

before_install:
  - gem update --system
  - gem --version

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load

script:
  - bundle exec rails test
  - bundle exec rails test:system
