language: ruby

rvm:
  - 2.4.1

cache:
  - bundler

env:
  - DB=postgres

services:
  - postgresql

script:
  - bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
  - bundle exec rails test
